"""Add region column to Missions

Revision ID: 0f4223d691c8
Revises: 540cfc2de301
Create Date: 2025-07-04 11:43:43.793196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4223d691c8'
down_revision = '540cfc2de301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))
        batch_op.alter_column('time_left',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('time_left',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('region')

    # ### end Alembic commands ###
