"""Add img column to Dragons

Revision ID: 1796030c502a
Revises: b59234eb8f9c
Create Date: 2025-07-01 16:40:54.635879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1796030c502a'
down_revision = 'b59234eb8f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
