"""Add last_fed, last_played columns

Revision ID: 2709a62d65b1
Revises: 609adc03b99c
Create Date: 2025-07-02 20:40:08.066385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2709a62d65b1'
down_revision = '609adc03b99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('happiness', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('last_fed', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_played', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.drop_column('last_played')
        batch_op.drop_column('last_fed')
        batch_op.drop_column('happiness')

    # ### end Alembic commands ###
