"""Make last_fed and last_played nullable

Revision ID: 540cfc2de301
Revises: 2709a62d65b1
Create Date: 2025-07-02 20:43:12.126951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540cfc2de301'
down_revision = '2709a62d65b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_played', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.drop_column('last_played')
        batch_op.drop_column('last_fed')

    # ### end Alembic commands ###
