"""Add hunger, happiness, last_fed, last_played columns

Revision ID: 609adc03b99c
Revises: c574ce92a5d7
Create Date: 2025-07-02 20:34:46.831965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609adc03b99c'
down_revision = 'c574ce92a5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hunger', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('last_fed', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('happiness', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('last_played', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.drop_column('last_played')
        batch_op.drop_column('happiness')
        batch_op.drop_column('last_fed')
        batch_op.drop_column('hunger')

    # ### end Alembic commands ###
