"""Add hunger column to DragonsOwned

Revision ID: c574ce92a5d7
Revises: 1796030c502a
Create Date: 2025-07-02 20:20:18.883588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c574ce92a5d7'
down_revision = '1796030c502a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hunger', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_fed', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('happiness', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_played', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons_owned', schema=None) as batch_op:
        batch_op.drop_column('last_played')
        batch_op.drop_column('happiness')
        batch_op.drop_column('last_fed')
        batch_op.drop_column('hunger')

    # ### end Alembic commands ###
